#!/bin/bash

hosts=( \
    'p2.hk1.towergood.com' \
    'p2.hk2.towergood.com' \
    'p2.hk3.towergood.com' \
    'p2.tw1.towergood.com' \
    'p2.sg1.towergood.com' \
    'p2.sg2.towergood.com' \
    'p2.jp1.towergood.com' \
    'p2.jp2.towergood.com' \
    'p2.jp3.towergood.com' \
    'p2.jp4.towergood.com' \
    'p2.us1.towergood.com' \
    'p2.us2.towergood.com' \
    'p2.us3.towergood.com' \
    'p2.us4.towergood.com' \
    'p2.us5.towergood.com' \
    'p2.us6.towergood.com' \
    )

for host in ${hosts[@]}; do
    echo -e '######## '${host}' ########'
    ping -c 4 $host
    echo -e ' '
    echo -e ' '
    echo -e ' '
done

echo -e '######## all done ########'
