#!/bin/bash

wget https://raw.githubusercontent.com/racaljk/hosts/master/hosts -O ~/Desktop/hosts
sed -i '' 's/# Modified hosts start/117.25.135.231  t.kinhop.com\
112.74.81.111   t.mengdaa.com\
117.25.135.237  fwgsvn\
\
# Modify hosts start/g' ~/Desktop/hosts
# echo 'this is your password' | sudo -S mv ~/Desktop/hosts /etc/hosts
sudo mv ~/Desktop/hosts /etc/hosts

/usr/bin/open ~/Desktop/installUpdateXcodePlugins
